name: upload artefacts to release on new tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: create release package
        run: echo "abcd" > my-release.1.txt
      - name: Get the version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: attach artefacts to release
        uses: softprops/action-gh-release@v1
        with:
          files: my-release.*.txt
          name: Release ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create release package 2
        run: echo "abcd" > my-2nd-release.2.txt
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: my-2nd-release.*.txt
          file_glob: true
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          overwrite: true
